from selection.strategies import RankBased, SUS, Roulette

MAX_COMPARATORS = 128
MIN_COMPARATORS = 3
COMPARATOR_LOWER_BOUND = 43
COMPARATOR_UPPER_BOUND = 45
NET_FAST_MUTATION_THRESH = 0.2
INPUT_FAST_MUTATION_THRESH = 0.2
NETWORK_SIZE = 13

N_EPOCHS = 130
N_ELITISM = 25
NET_MUTATION_P = 0.1
NET_MUTATION_CASES = [0.8, 0.1, 0.1]
NET_CROSSOVER_P = 0.6
NET_STRATEGY = RankBased(base=0.99)
NET_POP_SIZE = 3000
INPUT_MUTATION_P = 0.1
INPUT_CROSSOVER_P = 0.6
INPUT_STRATEGY = SUS()
INPUT_POP_SIZE = 1024
